### ISSUE TITLE
Bug generating flow diagram

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive-api#302]
To recreate:
```
git clone --recurse-submodules https://github.com/NCAR/music-box.git
cd music-box
docker build -t music-box-test .
docker run -p 8000:8000 -it music-box-test
```

In the browser:

Start Here > Select Example > Full Gas Mechanism
Run
Flow Diagram
Select "ALD2" from species list

Error message:
```
Internal Server Error: /get_flow
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/music-box-interactive/interactive/dashboard/views.py", line 117, in get_flow
    generate_flow_diagram(request.GET.dict())
  File "/music-box-interactive/interactive/dashboard/flow_diagram.py", line 775, in generate_flow_diagram
    net.show(path_to_template)
  File "/usr/local/lib/python3.9/site-packages/pyvis/network.py", line 551, in show
    self.write_html(name, local)
  File "/usr/local/lib/python3.9/site-packages/pyvis/network.py", line 533, in write_html
    shutil.rmtree(f"{tempdir}/lib")
  File "/usr/lib64/python3.9/shutil.py", line 737, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib64/python3.9/shutil.py", line 735, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
2022-11-29 02:06:50,089 - Internal Server Error: /get_flow
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/music-box-interactive/interactive/dashboard/views.py", line 117, in get_flow
    generate_flow_diagram(request.GET.dict())
  File "/music-box-interactive/interactive/dashboard/flow_diagram.py", line 775, in generate_flow_diagram
    net.show(path_to_template)
  File "/usr/local/lib/python3.9/site-packages/pyvis/network.py", line 551, in show
    self.write_html(name, local)
  File "/usr/local/lib/python3.9/site-packages/pyvis/network.py", line 533, in write_html
    shutil.rmtree(f"{tempdir}/lib")
  File "/usr/lib64/python3.9/shutil.py", line 737, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib64/python3.9/shutil.py", line 735, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
[29/Nov/2022 02:06:50] "GET /get_flow?includedSpecies=ALD2&blockedSpecies=&startStep=0&endStep=10800&maxArrowWidth=7&arrowScalingType=log&minMolval=0.000e%2B0&maxMolval=1.000e%2B0&currentMinValOfGraph=0&currentMaxValOfGraph=1&isPhysicsEnabled=false HTTP/1.1" 500 150349
```

**Comment by K20shores** [comment]
being fixed by #335
